version: '2.1'
orbs:
  node: circleci/node@4.6.0

jobs:
  unit_tests:
    executor:
      name: node/default
      tag: '16.0.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run unit tests"
          command: yarn test

  solhint:
    executor:
      name: node/default
      tag: '16.0.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run solhint and lint-check"
          command: |
            yarn solhint
            yarn lint-check

workflows:
  unit_tests:
    jobs:
      - unit_tests
  solhint:
    jobs:
      - solhint
